# Generated by Django 5.2.6 on 2025-09-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_product_code_product_uniq_product_code_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
