# Generated by Django 5.2.6 on 2025-12-11 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_notificationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='initial_stock',
            field=models.IntegerField(default=0, help_text='Stock when first received in'),
        ),
    ]
