# Generated by Django 5.2.6 on 2025-12-19 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_product_initial_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='ชื่อเทศกาล เช่น สงกราน, ปีใหม่', max_length=100)),
                ('description', models.TextField(blank=True, help_text='รายละเอียดเทศกาล', null=True)),
                ('start_date', models.DateField(help_text='วันเริ่มเทศกาล')),
                ('end_date', models.DateField(help_text='วันสิ้นสุดเทศกาล')),
                ('is_recurring', models.BooleanField(default=True, help_text='ประจำปี (True) หรือ ไม่ประจำปี (False)')),
                ('category', models.CharField(choices=[('new_year', 'ปีใหม่'), ('songkran', 'สงกราน'), ('festival', 'เทศกาล'), ('holiday', 'วันหยุด'), ('special', 'วันพิเศษ')], default='festival', max_length=50)),
                ('icon', models.CharField(default='🎉', help_text='emoji สำหรับแสดง', max_length=50)),
                ('color', models.CharField(default='#FF6B6B', help_text='สีสำหรับแสดงบน Calendar (#RRGGBB)', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Festival',
                'verbose_name_plural': 'Festivals',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='FestivalForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='หมายเหตุการคาดการณ์', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('festival', models.OneToOneField(help_text='เทศกาล', on_delete=django.db.models.deletion.CASCADE, related_name='forecast', to='inventory.festival')),
            ],
            options={
                'verbose_name': 'Festival Forecast',
                'verbose_name_plural': 'Festival Forecasts',
            },
        ),
        migrations.CreateModel(
            name='ForecastProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_quantity', models.IntegerField(default=0, help_text='จำนวนที่แนะนำให้เตรียม')),
                ('confidence', models.IntegerField(default=80, help_text='ความเชื่อมั่นของการแนะนำ (0-100%)')),
                ('notes', models.TextField(blank=True, help_text='หมายเหตุ', null=True)),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_forecasts', to='inventory.festivalforecast')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
            options={
                'ordering': ['-confidence', '-recommended_quantity'],
                'unique_together': {('forecast', 'product')},
            },
        ),
        migrations.AddField(
            model_name='festivalforecast',
            name='recommended_products',
            field=models.ManyToManyField(help_text='สินค้าที่ควรเตรียม', through='inventory.ForecastProduct', to='inventory.product'),
        ),
        migrations.CreateModel(
            name='BestSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_issued', models.IntegerField(default=0, help_text='จำนวนเบิกทั้งหมด')),
                ('percentage_increase', models.FloatField(default=0.0, help_text='เพิ่มขึ้นเปอร์เซ็นต์เมื่อเทียบกับ last_year')),
                ('last_year_count', models.IntegerField(default=0, help_text='จำนวนเบิกปีที่แล้ว')),
                ('this_year_count', models.IntegerField(default=0, help_text='จำนวนเบิกปีนี้')),
                ('rank', models.IntegerField(default=0, help_text='ลำดับที่ (1=ขายดีสุด)')),
                ('recorded_date', models.DateField(auto_now_add=True, help_text='วันที่บันทึก')),
                ('notes', models.TextField(blank=True, help_text='หมายเหตุเพิ่มเติม', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(help_text='สินค้า', on_delete=django.db.models.deletion.CASCADE, related_name='best_sellers', to='inventory.product')),
                ('festival', models.ForeignKey(help_text='เทศกาล', on_delete=django.db.models.deletion.CASCADE, related_name='best_sellers', to='inventory.festival')),
            ],
            options={
                'verbose_name': 'Best Seller',
                'verbose_name_plural': 'Best Sellers',
                'ordering': ['-rank', '-total_issued'],
                'indexes': [models.Index(fields=['festival', '-rank'], name='inventory_b_festiva_470d76_idx'), models.Index(fields=['product', 'festival'], name='inventory_b_product_309d7f_idx')],
                'unique_together': {('product', 'festival')},
            },
        ),
    ]
