# Generated by Django 5.2.6 on 2025-12-23 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_product_cost_price_product_selling_price_and_more'),
    ]

    operations = [
    ]
