# Generated by Django 5.2.6 on 2025-12-24 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_populate_cost_and_selling_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'รอดำเนินการ'), ('in_progress', 'กำลังดำเนินการ'), ('completed', 'เสร็จสิ้น'), ('cancelled', 'ยกเลิก')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'ต่ำ'), ('medium', 'ปกติ'), ('high', 'สูง'), ('urgent', 'ด่วน')], default='medium', max_length=20)),
                ('target_quantity', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('due_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('festival', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.festival')),
                ('products', models.ManyToManyField(blank=True, to='inventory.product')),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
    ]
