# Generated by Django 5.2.6 on 2025-12-24 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-priority', 'due_date'], 'verbose_name': 'งาน', 'verbose_name_plural': 'งาน'},
        ),
        migrations.AddField(
            model_name='task',
            name='checklist',
            field=models.JSONField(blank=True, default=list, help_text='ตัวอย่าง: [{"item": "สินค้า 10 ชิ้น", "done": false}]', null=True, verbose_name='รายการตรวจสอบ'),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='เสร็จเมื่อ'),
        ),
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='สร้างโดย'),
        ),
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tasks/', verbose_name='รูปภาพ'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('stock_replenishment', '🎁 เติมสินค้า'), ('product_listing', '📦 ขึ้นแคตตาล็อก'), ('visual_merchandising', '🎨 จัดท่ากระบาย'), ('inventory_check', '🔍 ตรวจสต็อก'), ('preparation', '📋 เตรียมสินค้า'), ('purchase_followup', '📞 ติดตามสั่งซื้อ'), ('other', '📝 อื่นๆ')], default='other', max_length=50, verbose_name='ประเภทงาน'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='มอบหมายให้'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(verbose_name='รายละเอียด'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(verbose_name='วันกำหนด'),
        ),
        migrations.AlterField(
            model_name='task',
            name='festival',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='inventory.festival', verbose_name='เทศกาล (ถ้ามี)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='หมายเหตุ/รายงานผล'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', '🟢 ต่ำ'), ('medium', '🟡 ปกติ'), ('high', '🔴 สูง'), ('urgent', '⚠️ ด่วน')], default='medium', max_length=20, verbose_name='ลำดับความสำคัญ'),
        ),
        migrations.AlterField(
            model_name='task',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='inventory.product', verbose_name='สินค้าที่เกี่ยวข้อง'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', '⏳ รอรับ'), ('in_progress', '⚙️ กำลังทำ'), ('completed', '✅ เสร็จ'), ('cancelled', '❌ ยกเลิก')], default='pending', max_length=20, verbose_name='สถานะ'),
        ),
        migrations.AlterField(
            model_name='task',
            name='target_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='จำนวนเป้าหมาย'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=255, verbose_name='ชื่องาน'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='อัปเดตเมื่อ'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_to', 'status'], name='inventory_t_assigne_c84f7f_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date'], name='inventory_t_due_dat_e00c4e_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='inventory_t_status_d60996_idx'),
        ),
    ]
