# Generated by Django 5.2.6 on 2026-01-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_task_options_task_checklist_task_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='notes',
            field=models.TextField(blank=True, help_text='หมายเหตุ/แจ้งเตือนให้พนักงาน', null=True),
        ),
        migrations.AddField(
            model_name='festival',
            name='preparation_tasks',
            field=models.TextField(blank=True, help_text='รายการสิ่งที่ต้องเตรียม (แยกด้วย ,)', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('stock_replenishment', '🎁 เติมสินค้า'), ('stock_issue', '📤 เบิกสต๊อก'), ('inventory_check', '🔍 ตรวจสต็อก'), ('preparation', '📋 เตรียมสินค้า'), ('other', '📝 อื่นๆ')], default='other', max_length=50, verbose_name='ประเภทงาน'),
        ),
    ]
