# Generated by Django 5.2.6 on 2026-01-10 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_festival_notes_festival_preparation_tasks_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ชื่อ')),
                ('date', models.DateField(verbose_name='วันที่')),
                ('event_type', models.CharField(choices=[('reminder', 'เตือนความจำ'), ('stock', 'เตรียมสต็อก'), ('promotion', 'โปรโมชั่น'), ('meeting', 'นัดหมาย'), ('other', 'อื่นๆ')], default='reminder', max_length=20, verbose_name='ประเภท')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ')),
                ('is_shared', models.BooleanField(default=True, verbose_name='แชร์ให้ทุกคน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_events', to=settings.AUTH_USER_MODEL, verbose_name='สร้างโดย')),
            ],
            options={
                'verbose_name': 'บันทึกของฉัน',
                'verbose_name_plural': 'บันทึกของฉัน',
                'ordering': ['date', '-created_at'],
            },
        ),
    ]
