# Generated by Django 5.2.6 on 2026-01-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_customevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customevent',
            options={'ordering': ['-priority', 'date', '-created_at'], 'verbose_name': 'บันทึกของฉัน', 'verbose_name_plural': 'บันทึกของฉัน'},
        ),
        migrations.AddField(
            model_name='customevent',
            name='priority',
            field=models.CharField(choices=[('low', 'ต่ำ'), ('medium', 'ปกติ'), ('high', 'สูง'), ('urgent', 'ด่วน')], default='medium', max_length=20, verbose_name='ระดับความสำคัญ'),
        ),
        migrations.AlterField(
            model_name='customevent',
            name='event_type',
            field=models.CharField(choices=[('stock_order', 'สั่งซื้อสินค้า'), ('promotion', 'จัดโปรโมชั่น'), ('delivery', 'รับ/ส่งสินค้า'), ('meeting', 'ประชุม/นัดหมาย'), ('other', 'อื่นๆ')], default='stock_check', max_length=20, verbose_name='ประเภท'),
        ),
    ]
