# Generated by Django 5.2.6 on 2026-01-31 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_alter_customevent_options_customevent_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customevent',
            name='event_type',
            field=models.CharField(choices=[('stock_order', 'สั่งซื้อสินค้า'), ('promotion', 'จัดโปรโมชั่น'), ('delivery', 'รับ/ส่งสินค้า'), ('meeting', 'ประชุม/นัดหมาย'), ('other', 'อื่นๆ')], default='stock_order', max_length=20, verbose_name='ประเภท'),
        ),
    ]
