# Generated by Django 5.2.6 on 2026-02-15 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festivalforecast',
            name='festival',
        ),
        migrations.RemoveField(
            model_name='festivalforecast',
            name='recommended_products',
        ),
        migrations.RemoveField(
            model_name='forecastproduct',
            name='forecast',
        ),
        migrations.AlterUniqueTogether(
            name='forecastproduct',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='forecastproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='user',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.DeleteModel(
            name='FestivalForecast',
        ),
        migrations.DeleteModel(
            name='ForecastProduct',
        ),
        migrations.DeleteModel(
            name='NotificationSettings',
        ),
    ]
