# Generated by Django 5.2.6 on 2026-02-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_remove_festivalforecast_festival_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('pending', 'รอดำเนินการ'), ('completed', 'เสร็จสิ้น'), ('cancelled', 'ยกเลิก')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='customevent',
            name='event_type',
            field=models.CharField(choices=[('stock_order', 'สั่งซื้อสินค้า'), ('stock_check', 'ตรวจนับสต็อก'), ('delivery', 'รับ/ส่งสินค้า'), ('meeting', 'ประชุม/นัดหมาย'), ('other', 'อื่นๆ')], default='stock_order', max_length=20, verbose_name='ประเภท'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='initial_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
