# Generated by Django 5.2.6 on 2026-02-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_alter_task_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('stock_replenishment', '🎁 เติมสินค้า'), ('stock_issue', '📤 เบิกสต๊อก'), ('inventory_check', '🔍 ตรวจสต็อก'), ('preparation', '📋 เตรียมสินค้า'), ('other', '📝 อื่นๆ')], default='other', max_length=50, verbose_name='ประเภทงาน'),
        ),
    ]
