# Generated by Django 5.2.6 on 2026-03-07 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_remove_product_cost_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BestSeller',
        ),
    ]
