# Generated by Django 5.2.6 on 2026-05-05 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_delete_bestseller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='festival',
        ),
        migrations.RemoveField(
            model_name='task',
            name='products',
        ),
    ]
