# Generated by Django 5.2.6 on 2025-11-26 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_avatar_user_profile_image'),
    ]

    operations = [
    ]
