# Generated by Django 5.2.6 on 2025-11-26 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_profile_image'),
    ]

    operations = [
    ]
