# Generated by Django 5.2.6 on 2025-12-10 15:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_notificationsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationsettings',
            options={'verbose_name': 'Notification Setting', 'verbose_name_plural': 'Notification Settings'},
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='low_stock',
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='out_of_stock',
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='stock_movement',
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='line_user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
