# Generated by Django 5.2.6 on 2026-02-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin/Owner'), ('employee', 'Employee')], default='employee', max_length=20, verbose_name='บทบาท'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
