# Generated by Django 5.2.6 on 2025-12-09 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_user_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='LINE User ID')),
                ('low_stock', models.BooleanField(default=True, verbose_name='แจ้งเตือนสินค้าใกล้หมด')),
                ('out_of_stock', models.BooleanField(default=True, verbose_name='แจ้งเตือนสินค้าหมด')),
                ('stock_movement', models.BooleanField(default=True, verbose_name='แจ้งเตือนการเคลื่อนไหวสต็อก')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
